// coins.js - 100 coins with online icons for Deposit page
const COINS = [
  { symbol: "BTC", name: "Bitcoin", icon: "https://cryptoicons.org/api/icon/btc/64" },
  { symbol: "ETH", name: "Ethereum", icon: "https://cryptoicons.org/api/icon/eth/64" },
  { symbol: "USDT", name: "Tether", icon: "https://cryptoicons.org/api/icon/usdt/64" },
  { symbol: "BNB", name: "Binance Coin", icon: "https://cryptoicons.org/api/icon/bnb/64" },
  { symbol: "ADA", name: "Cardano", icon: "https://cryptoicons.org/api/icon/ada/64" },
  { symbol: "XRP", name: "XRP", icon: "https://cryptoicons.org/api/icon/xrp/64" },
  { symbol: "SOL", name: "Solana", icon: "https://cryptoicons.org/api/icon/sol/64" },
  { symbol: "DOT", name: "Polkadot", icon: "https://cryptoicons.org/api/icon/dot/64" },
  { symbol: "DOGE", name: "Dogecoin", icon: "https://cryptoicons.org/api/icon/doge/64" },
  { symbol: "AVAX", name: "Avalanche", icon: "https://cryptoicons.org/api/icon/avax/64" },
  { symbol: "SHIB", name: "Shiba Inu", icon: "https://cryptoicons.org/api/icon/shib/64" },
  { symbol: "MATIC", name: "Polygon", icon: "https://cryptoicons.org/api/icon/matic/64" },
  { symbol: "LTC", name: "Litecoin", icon: "https://cryptoicons.org/api/icon/ltc/64" },
  { symbol: "ATOM", name: "Cosmos", icon: "https://cryptoicons.org/api/icon/atom/64" },
  { symbol: "LINK", name: "Chainlink", icon: "https://cryptoicons.org/api/icon/link/64" },
  { symbol: "ALGO", name: "Algorand", icon: "https://cryptoicons.org/api/icon/algo/64" },
  { symbol: "XLM", name: "Stellar", icon: "https://cryptoicons.org/api/icon/xlm/64" },
  { symbol: "VET", name: "VeChain", icon: "https://cryptoicons.org/api/icon/vet/64" },
  { symbol: "TRX", name: "TRON", icon: "https://cryptoicons.org/api/icon/trx/64" },
  { symbol: "FTT", name: "FTX Token", icon: "https://cryptoicons.org/api/icon/ftt/64" },
  { symbol: "FIL", name: "Filecoin", icon: "https://cryptoicons.org/api/icon/fil/64" },
  { symbol: "TON", name: "Toncoin", icon: "https://cryptoicons.org/api/icon/ton/64" },
  { symbol: "HBAR", name: "Hedera", icon: "https://cryptoicons.org/api/icon/hbar/64" },
  { symbol: "MANA", name: "Decentraland", icon: "https://cryptoicons.org/api/icon/mana/64" },
  { symbol: "SAND", name: "The Sandbox", icon: "https://cryptoicons.org/api/icon/sand/64" },
  { symbol: "APE", name: "ApeCoin", icon: "https://cryptoicons.org/api/icon/ape/64" },
  { symbol: "CHZ", name: "Chiliz", icon: "https://cryptoicons.org/api/icon/chz/64" },
  { symbol: "ICP", name: "Internet Computer", icon: "https://cryptoicons.org/api/icon/icp/64" },
  { symbol: "EGLD", name: "Elrond", icon: "https://cryptoicons.org/api/icon/egld/64" },
  { symbol: "XTZ", name: "Tezos", icon: "https://cryptoicons.org/api/icon/xtz/64" },
  { symbol: "FLOW", name: "Flow", icon: "https://cryptoicons.org/api/icon/flow/64" },
  { symbol: "QNT", name: "Quant", icon: "https://cryptoicons.org/api/icon/qnt/64" },
  { symbol: "NEAR", name: "NEAR Protocol", icon: "https://cryptoicons.org/api/icon/near/64" },
  { symbol: "VTHO", name: "VeThor Token", icon: "https://cryptoicons.org/api/icon/vtho/64" },
  { symbol: "KLAY", name: "Klaytn", icon: "https://cryptoicons.org/api/icon/klay/64" },
  { symbol: "STX", name: "Stacks", icon: "https://cryptoicons.org/api/icon/stx/64" },
  { symbol: "GALA", name: "Gala", icon: "https://cryptoicons.org/api/icon/gala/64" },
  { symbol: "RUNE", name: "THORChain", icon: "https://cryptoicons.org/api/icon/rune/64" },
  { symbol: "MIOTA", name: "IOTA", icon: "https://cryptoicons.org/api/icon/miota/64" },
  { symbol: "KSM", name: "Kusama", icon: "https://cryptoicons.org/api/icon/ksm/64" },
  { symbol: "ZEC", name: "Zcash", icon: "https://cryptoicons.org/api/icon/zec/64" },
  { symbol: "BAT", name: "Basic Attention Token", icon: "https://cryptoicons.org/api/icon/bat/64" },
  { symbol: "DASH", name: "Dash", icon: "https://cryptoicons.org/api/icon/dash/64" },
  { symbol: "ENJ", name: "Enjin Coin", icon: "https://cryptoicons.org/api/icon/enj/64" },
  { symbol: "CRO", name: "Cronos", icon: "https://cryptoicons.org/api/icon/cro/64" },
  { symbol: "RVN", name: "Ravencoin", icon: "https://cryptoicons.org/api/icon/rvn/64" },
  { symbol: "FTM", name: "Fantom", icon: "https://cryptoicons.org/api/icon/ftm/64" },
  { symbol: "ONE", name: "Harmony", icon: "https://cryptoicons.org/api/icon/one/64" },
  { symbol: "TFUEL", name: "Theta Fuel", icon: "https://cryptoicons.org/api/icon/tfuel/64" },
  { symbol: "DCR", name: "Decred", icon: "https://cryptoicons.org/api/icon/dcr/64" },
  { symbol: "LRC", name: "Loopring", icon: "https://cryptoicons.org/api/icon/lrc/64" },
  { symbol: "NEO", name: "NEO", icon: "https://cryptoicons.org/api/icon/neo/64" },
  { symbol: "ZIL", name: "Zilliqa", icon: "https://cryptoicons.org/api/icon/zil/64" },
  { symbol: "OMG", name: "OMG Network", icon: "https://cryptoicons.org/api/icon/omg/64" },
  { symbol: "HOT", name: "Holo", icon: "https://cryptoicons.org/api/icon/hot/64" },
  { symbol: "ICX", name: "ICON", icon: "https://cryptoicons.org/api/icon/icx/64" },
  { symbol: "BTT", name: "BitTorrent", icon: "https://cryptoicons.org/api/icon/btt/64" },
  { symbol: "KNC", name: "Kyber Network", icon: "https://cryptoicons.org/api/icon/knc/64" },
  { symbol: "GRT", name: "The Graph", icon: "https://cryptoicons.org/api/icon/grt/64" },
  { symbol: "SUSHI", name: "SushiSwap", icon: "https://cryptoicons.org/api/icon/sushi/64" },
  { symbol: "COMP", name: "Compound", icon: "https://cryptoicons.org/api/icon/comp/64" },
  { symbol: "AAVE", name: "Aave", icon: "https://cryptoicons.org/api/icon/aave/64" },
  { symbol: "SNX", name: "Synthetix", icon: "https://cryptoicons.org/api/icon/snx/64" },
  { symbol: "YFI", name: "Yearn.Finance", icon: "https://cryptoicons.org/api/icon/yfi/64" },
  { symbol: "CEL", name: "Celsius", icon: "https://cryptoicons.org/api/icon/cel/64" },
  { symbol: "1INCH", name: "1inch", icon: "https://cryptoicons.org/api/icon/1inch/64" },
  { symbol: "BAL", name: "Balancer", icon: "https://cryptoicons.org/api/icon/bal/64" },
  { symbol: "REN", name: "Ren", icon: "https://cryptoicons.org/api/icon/ren/64" },
  { symbol: "ANKR", name: "Ankr", icon: "https://cryptoicons.org/api/icon/ankr/64" },
  { symbol: "KAVA", name: "Kava", icon: "https://cryptoicons.org/api/icon/kava/64" },
  { symbol: "GNO", name: "Gnosis", icon: "https://cryptoicons.org/api/icon/gno/64" },
  { symbol: "HNT", name: "Helium", icon: "https://cryptoicons.org/api/icon/hnt/64" },
  { symbol: "STORJ", name: "Storj", icon: "https://cryptoicons.org/api/icon/storj/64" },
  { symbol: "AR", name: "Arweave", icon: "https://cryptoicons.org/api/icon/ar/64" },
  { symbol: "NEXO", name: "Nexo", icon: "https://cryptoicons.org/api/icon/nexo/64" },
  { symbol: "CVX", name: "Convex Finance", icon: "https://cryptoicons.org/api/icon/cvx/64" },
  { symbol: "LPT", name: "Livepeer", icon: "https://cryptoicons.org/api/icon/lpt/64" },
  { symbol: "OCEAN", name: "Ocean Protocol", icon: "https://cryptoicons.org/api/icon/ocean/64" },
  { symbol: "GTC", name: "Gitcoin", icon: "https://cryptoicons.org/api/icon/gtc/64" },
  { symbol: "UMA", name: "UMA", icon: "https://cryptoicons.org/api/icon/uma/64" },
  { symbol: "FET", name: "Fetch.ai", icon: "https://cryptoicons.org/api/icon/fet/64" },
  { symbol: "SXP", name: "Swipe", icon: "https://cryptoicons.org/api/icon/sxp/64" },
  { symbol: "CVC", name: "Civic", icon: "https://cryptoicons.org/api/icon/cvc/64" },
  { symbol: "RAY", name: "Raydium", icon: "https://cryptoicons.org/api/icon/ray/64" },
  { symbol: "KDA", name: "Kadena", icon: "https://cryptoicons.org/api/icon/kda/64" },
  { symbol: "ENS", name: "Ethereum Name Service", icon: "https://cryptoicons.org/api/icon/ens/64" },
  { symbol: "FLUX", name: "Flux", icon: "https://cryptoicons.org/api/icon/flux/64" },
  { symbol: "CELR", name: "Celer Network", icon: "https://cryptoicons.org/api/icon/celr/64" },
  { symbol: "LDO", name: "Lido DAO", icon: "https://cryptoicons.org/api/icon/ldo/64" },
  { symbol: "TWT", name: "Trust Wallet Token", icon: "https://cryptoicons.org/api/icon/twt/64" },
  { symbol: "ROSE", name: "Oasis Network", icon: "https://cryptoicons.org/api/icon/rose/64" },
  { symbol: "IOST", name: "IOST", icon: "https://cryptoicons.org/api/icon/iost/64" }
];
