// coins.js
const COINS = [
  { symbol: "BTC", name: "Bitcoin", icon: "icons/btc.png" },
  { symbol: "ETH", name: "Ethereum", icon: "icons/eth.png" },
  { symbol: "USDT", name: "Tether", icon: "icons/usdt.png" },
  { symbol: "BNB", name: "Binance Coin", icon: "icons/bnb.png" },
  { symbol: "ADA", name: "Cardano", icon: "icons/ada.png" },
  { symbol: "XRP", name: "XRP", icon: "icons/xrp.png" },
  { symbol: "SOL", name: "Solana", icon: "icons/sol.png" },
  { symbol: "DOT", name: "Polkadot", icon: "icons/dot.png" },
  { symbol: "DOGE", name: "Dogecoin", icon: "icons/doge.png" },
  { symbol: "AVAX", name: "Avalanche", icon: "icons/avax.png" },
  { symbol: "SHIB", name: "Shiba Inu", icon: "icons/shib.png" },
  { symbol: "MATIC", name: "Polygon", icon: "icons/matic.png" },
  { symbol: "LTC", name: "Litecoin", icon: "icons/ltc.png" },
  { symbol: "ATOM", name: "Cosmos", icon: "icons/atom.png" },
  { symbol: "LINK", name: "Chainlink", icon: "icons/link.png" },
  { symbol: "ALGO", name: "Algorand", icon: "icons/algo.png" },
  { symbol: "XLM", name: "Stellar", icon: "icons/xlm.png" },
  { symbol: "VET", name: "VeChain", icon: "icons/vet.png" },
  { symbol: "TRX", name: "TRON", icon: "icons/trx.png" },
  { symbol: "FTT", name: "FTX Token", icon: "icons/ftt.png" },
  { symbol: "FIL", name: "Filecoin", icon: "icons/fil.png" },
  { symbol: "TON", name: "Toncoin", icon: "icons/ton.png" },
  { symbol: "HBAR", name: "Hedera", icon: "icons/hbar.png" },
  { symbol: "MANA", name: "Decentraland", icon: "icons/mana.png" },
  { symbol: "SAND", name: "The Sandbox", icon: "icons/sand.png" },
  { symbol: "APE", name: "ApeCoin", icon: "icons/ape.png" },
  { symbol: "CHZ", name: "Chiliz", icon: "icons/chz.png" },
  { symbol: "ICP", name: "Internet Computer", icon: "icons/icp.png" },
  { symbol: "EGLD", name: "Elrond", icon: "icons/egld.png" },
  { symbol: "XTZ", name: "Tezos", icon: "icons/xtz.png" },
  { symbol: "FLOW", name: "Flow", icon: "icons/flow.png" },
  { symbol: "QNT", name: "Quant", icon: "icons/qnt.png" },
  { symbol: "NEAR", name: "NEAR Protocol", icon: "icons/near.png" },
  { symbol: "VTHO", name: "VeThor Token", icon: "icons/vtho.png" },
  { symbol: "KLAY", name: "Klaytn", icon: "icons/klay.png" },
  { symbol: "STX", name: "Stacks", icon: "icons/stx.png" },
  { symbol: "GALA", name: "Gala", icon: "icons/gala.png" },
  { symbol: "RUNE", name: "THORChain", icon: "icons/rune.png" },
  { symbol: "MIOTA", name: "IOTA", icon: "icons/miota.png" },
  { symbol: "KSM", name: "Kusama", icon: "icons/ksm.png" },
  { symbol: "ZEC", name: "Zcash", icon: "icons/zec.png" },
  { symbol: "BAT", name: "Basic Attention Token", icon: "icons/bat.png" },
  { symbol: "DASH", name: "Dash", icon: "icons/dash.png" },
  { symbol: "ENJ", name: "Enjin Coin", icon: "icons/enj.png" },
  { symbol: "CRO", name: "Cronos", icon: "icons/cro.png" },
  { symbol: "RVN", name: "Ravencoin", icon: "icons/rvn.png" },
  { symbol: "FTM", name: "Fantom", icon: "icons/ftm.png" },
  { symbol: "ONE", name: "Harmony", icon: "icons/one.png" },
  { symbol: "TFUEL", name: "Theta Fuel", icon: "icons/tfuel.png" },
  { symbol: "DCR", name: "Decred", icon: "icons/dcr.png" },
  { symbol: "LRC", name: "Loopring", icon: "icons/lrc.png" },
  { symbol: "NEO", name: "NEO", icon: "icons/neo.png" },
  { symbol: "ZIL", name: "Zilliqa", icon: "icons/zil.png" },
  { symbol: "OMG", name: "OMG Network", icon: "icons/omg.png" },
  { symbol: "HOT", name: "Holo", icon: "icons/hot.png" },
  { symbol: "ICX", name: "ICON", icon: "icons/icx.png" },
  { symbol: "BTT", name: "BitTorrent", icon: "icons/btt.png" },
  { symbol: "KNC", name: "Kyber Network", icon: "icons/knc.png" },
  { symbol: "GRT", name: "The Graph", icon: "icons/grt.png" },
  { symbol: "SUSHI", name: "SushiSwap", icon: "icons/sushi.png" },
  { symbol: "COMP", name: "Compound", icon: "icons/comp.png" },
  { symbol: "AAVE", name: "Aave", icon: "icons/aave.png" },
  { symbol: "SNX", name: "Synthetix", icon: "icons/snx.png" },
  { symbol: "YFI", name: "Yearn.Finance", icon: "icons/yfi.png" },
  { symbol: "CEL", name: "Celsius", icon: "icons/cel.png" },
  { symbol: "1INCH", name: "1inch", icon: "icons/1inch.png" },
  { symbol: "BAL", name: "Balancer", icon: "icons/bal.png" },
  { symbol: "REN", name: "Ren", icon: "icons/ren.png" },
  { symbol: "BAT", name: "Basic Attention Token", icon: "icons/bat.png" },
  { symbol: "RVN", name: "Ravencoin", icon: "icons/rvn.png" },
  { symbol: "CHZ", name: "Chiliz", icon: "icons/chz.png" },
  { symbol: "ANKR", name: "Ankr", icon: "icons/ankr.png" },
  { symbol: "KAVA", name: "Kava", icon: "icons/kava.png" },
  { symbol: "GNO", name: "Gnosis", icon: "icons/gno.png" },
  { symbol: "HNT", name: "Helium", icon: "icons/hnt.png" },
  { symbol: "STORJ", name: "Storj", icon: "icons/storj.png" },
  { symbol: "AR", name: "Arweave", icon: "icons/ar.png" },
  { symbol: "NEXO", name: "Nexo", icon: "icons/nexo.png" },
  { symbol: "CVX", name: "Convex Finance", icon: "icons/cvx.png" },
  { symbol: "LPT", name: "Livepeer", icon: "icons/lpt.png" },
  { symbol: "OCEAN", name: "Ocean Protocol", icon: "icons/ocean.png" },
  { symbol: "GTC", name: "Gitcoin", icon: "icons/gtc.png" },
  { symbol: "UMA", name: "UMA", icon: "icons/uma.png" },
  { symbol: "FET", name: "Fetch.ai", icon: "icons/fet.png" },
  { symbol: "ANKR", name: "Ankr", icon: "icons/ankr.png" },
  { symbol: "SXP", name: "Swipe", icon: "icons/sxp.png" },
  { symbol: "CVC", name: "Civic", icon: "icons/cvc.png" },
  { symbol: "RAY", name: "Raydium", icon: "icons/ray.png" },
  { symbol: "RVN", name: "Ravencoin", icon: "icons/rvn.png" },
  { symbol: "KDA", name: "Kadena", icon: "icons/kda.png" },
  { symbol: "ENS", name: "Ethereum Name Service", icon: "icons/ens.png" },
  { symbol: "FLUX", name: "Flux", icon: "icons/flux.png" },
  { symbol: "CELR", name: "Celer Network", icon: "icons/celr.png" },
  { symbol: "LDO", name: "Lido DAO", icon: "icons/ldo.png" },
  { symbol: "TWT", name: "Trust Wallet Token", icon: "icons/twt.png" },
  { symbol: "ROSE", name: "Oasis Network", icon: "icons/rose.png" },
  { symbol: "GNO", name: "Gnosis", icon: "icons/gno.png" },
  { symbol: "QNT", name: "Quant", icon: "icons/qnt.png" },
  { symbol: "ONE", name: "Harmony", icon: "icons/one.png" },
  { symbol: "IOST", name: "IOST", icon: "icons/iost.png" },
  { symbol: "KSM", name: "Kusama", icon: "icons/ksm.png" }
];
