// coins.js
const COINS = [
  { symbol: "BTC", name: "Bitcoin", icon: "https://assets.coingecko.com/coins/images/1/small/bitcoin.png" },
  { symbol: "ETH", name: "Ethereum", icon: "https://assets.coingecko.com/coins/images/279/small/ethereum.png" },
  { symbol: "USDT", name: "Tether", icon: "https://assets.coingecko.com/coins/images/325/small/Tether.png" },
  { symbol: "BNB", name: "BNB", icon: "https://assets.coingecko.com/coins/images/825/small/bnb-icon2_2x.png" },
  { symbol: "USDC", name: "USD Coin", icon: "https://assets.coingecko.com/coins/images/6319/small/USD_Coin_icon.png" },
  { symbol: "XRP", name: "XRP", icon: "https://assets.coingecko.com/coins/images/44/small/xrp-symbol-white-128.png" },
  { symbol: "ADA", name: "Cardano", icon: "https://assets.coingecko.com/coins/images/975/small/cardano.png" },
  { symbol: "DOGE", name: "Dogecoin", icon: "https://assets.coingecko.com/coins/images/5/small/dogecoin.png" },
  { symbol: "SOL", name: "Solana", icon: "https://assets.coingecko.com/coins/images/4128/small/solana.png" },
  { symbol: "TRX", name: "TRON", icon: "https://assets.coingecko.com/coins/images/1094/small/tron-logo.png" },

  { symbol: "DOT", name: "Polkadot", icon: "https://assets.coingecko.com/coins/images/12171/small/polkadot.png" },
  { symbol: "MATIC", name: "Polygon", icon: "https://assets.coingecko.com/coins/images/4713/small/polygon.png" },
  { symbol: "LTC", name: "Litecoin", icon: "https://assets.coingecko.com/coins/images/2/small/litecoin.png" },
  { symbol: "SHIB", name: "Shiba Inu", icon: "https://assets.coingecko.com/coins/images/11939/small/shiba.png" },
  { symbol: "AVAX", name: "Avalanche", icon: "https://assets.coingecko.com/coins/images/12559/small/coin-round-red.png" },
  { symbol: "DAI", name: "Dai", icon: "https://assets.coingecko.com/coins/images/9956/small/Badge_Dai.png" },
  { symbol: "ATOM", name: "Cosmos", icon: "https://assets.coingecko.com/coins/images/1481/small/cosmos_hub.png" },
  { symbol: "LINK", name: "Chainlink", icon: "https://assets.coingecko.com/coins/images/877/small/chainlink-new-logo.png" },
  { symbol: "ETC", name: "Ethereum Classic", icon: "https://assets.coingecko.com/coins/images/453/small/ethereum-classic-logo.png" },
  { symbol: "XMR", name: "Monero", icon: "https://assets.coingecko.com/coins/images/69/small/monero_logo.png" },

  { symbol: "BCH", name: "Bitcoin Cash", icon: "https://assets.coingecko.com/coins/images/780/small/bitcoin-cash-circle.png" },
  { symbol: "ICP", name: "Internet Computer", icon: "https://assets.coingecko.com/coins/images/14495/small/Internet_Computer_logo.png" },
  { symbol: "FIL", name: "Filecoin", icon: "https://assets.coingecko.com/coins/images/12817/small/filecoin.png" },
  { symbol: "APT", name: "Aptos", icon: "https://assets.coingecko.com/coins/images/26455/small/aptos_round.png" },
  { symbol: "HBAR", name: "Hedera", icon: "https://assets.coingecko.com/coins/images/3688/small/hbar.png" },
  { symbol: "NEAR", name: "NEAR Protocol", icon: "https://assets.coingecko.com/coins/images/10365/small/near.png" },
  { symbol: "VET", name: "VeChain", icon: "https://assets.coingecko.com/coins/images/1167/small/VeChain-Logo-768x725.png" },
  { symbol: "ALGO", name: "Algorand", icon: "https://assets.coingecko.com/coins/images/4380/small/download.png" },
  { symbol: "QNT", name: "Quant", icon: "https://assets.coingecko.com/coins/images/3370/small/quant.png" },
  { symbol: "EGLD", name: "MultiversX", icon: "https://assets.coingecko.com/coins/images/12335/small/egld.png" },

  { symbol: "AAVE", name: "Aave", icon: "https://assets.coingecko.com/coins/images/12645/small/AAVE.png" },
  { symbol: "SAND", name: "The Sandbox", icon: "https://assets.coingecko.com/coins/images/12129/small/sandbox_logo.jpg" },
  { symbol: "MANA", name: "Decentraland", icon: "https://assets.coingecko.com/coins/images/878/small/decentraland-mana.png" },
  { symbol: "XTZ", name: "Tezos", icon: "https://assets.coingecko.com/coins/images/976/small/Tezos-logo.png" },
  { symbol: "THETA", name: "Theta Network", icon: "https://assets.coingecko.com/coins/images/2538/small/theta-token-logo.png" },
  { symbol: "AXS", name: "Axie Infinity", icon: "https://assets.coingecko.com/coins/images/13029/small/axie_infinity_logo.png" },
  { symbol: "FLOW", name: "Flow", icon: "https://assets.coingecko.com/coins/images/13446/small/flow_logo.png" },
  { symbol: "KCS", name: "KuCoin Token", icon: "https://assets.coingecko.com/coins/images/1047/small/sa9z79.png" },
  { symbol: "FTM", name: "Fantom", icon: "https://assets.coingecko.com/coins/images/4001/small/Fantom.png" },
  { symbol: "GRT", name: "The Graph", icon: "https://assets.coingecko.com/coins/images/13397/small/Graph_Token.png" },

  { symbol: "RUNE", name: "THORChain", icon: "https://assets.coingecko.com/coins/images/6595/small/RUNE.png" },
  { symbol: "KAVA", name: "Kava", icon: "https://assets.coingecko.com/coins/images/9761/small/kava.png" },
  { symbol: "CRV", name: "Curve DAO", icon: "https://assets.coingecko.com/coins/images/12124/small/Curve.png" },
  { symbol: "LDO", name: "Lido DAO", icon: "https://assets.coingecko.com/coins/images/13573/small/Lido_DAO.png" },
  { symbol: "MINA", name: "Mina", icon: "https://assets.coingecko.com/coins/images/15628/small/mina.png" },
  { symbol: "SNX", name: "Synthetix", icon: "https://assets.coingecko.com/coins/images/3406/small/SNX.png" },
  { symbol: "ZEC", name: "Zcash", icon: "https://assets.coingecko.com/coins/images/486/small/circle-zcash-color.png" },
  { symbol: "DASH", name: "Dash", icon: "https://assets.coingecko.com/coins/images/19/small/dash-logo.png" },
  { symbol: "ENJ", name: "Enjin Coin", icon: "https://assets.coingecko.com/coins/images/1102/small/enjin-coin-logo.png" },
  { symbol: "CHZ", name: "Chiliz", icon: "https://assets.coingecko.com/coins/images/8834/small/Chiliz.png" }
];
